### PR TITLE
github-deploystatus and circleci-download

### PR DESCRIPTION
**Pull request by mastoj**
This adds two actions:

* github-deploystatus - used to update the deploy status
* circleci-download - used to download artifacts from circleci

### CODE REVIEW

**Comment by mastoj** [comment]
@judoole I'll have this PR to add both, so I closed the other one.

Not sure about the linting stuff.

**Comment by mastoj** [comment]
@judoole I deleted the github-deploy stuff and it started working. Let me know if you think this looks good and I'll merge and tag it.

**Comment by mastoj** [comment]
Do you have an update here @judoole? I agree that checking in the node_modules is far from ideal, but I also think that the work arounds available is not better. Moving to docker might be an option if the node_modules folder is a big issue.

**Comment by judoole** [comment]
Closing this one as code is moved into it's own repository https://github.com/unacast/actions-github-deployment-status

**Comment by judoole** [comment]
Wrong reason for closing. Sorry for that. This is the circleCI download... Well, if we wan't to start using it again. Re-open.

**Pull request closed without merging**
